# Generated by Django 3.0.4 on 2020-06-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoComApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(null=True, upload_to='product images'),
        ),
    ]
