# Generated by Django 3.0.4 on 2020-06-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoComApp', '0003_auto_20200612_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='products',
            field=models.ManyToManyField(null=True, to='autoComApp.Product'),
        ),
    ]
