# Generated by Django 3.0.4 on 2020-06-12 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoComApp', '0004_productcategory_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
